// FILE NÀY ĐƯỢC SINH TỰ ĐỘNG — ĐỪNG SỬA TAY.
// Nguồn: supabase/migrations/20260723090600_sales_tax_by_city.sql
// Sinh lại bằng: node scripts/sync-tax-data.mjs
//
// Số liệu là ƯỚC LƯỢNG KHỞI ĐIỂM, chưa được xác minh với cơ quan thuế của bang.

export type TaxJurisdiction = {
  /** Mã bang hai chữ, ví dụ "CA". */
  state: string;
  /** Tên thành phố, hoặc "*" nghĩa là mức mặc định của cả bang. */
  city: string;
  /** Thuế suất hàng hoá thường, dạng thập phân (0.095 = 9.5%). */
  general: number;
  /** Thuế suất hàng tạp hoá đủ điều kiện. */
  grocery: number;
  notes?: string;
};

export const taxJurisdictions: TaxJurisdiction[] = [
  { state: "AK", city: "*", general: 0, grocery: 0, notes: "Không có thuế cấp bang; một số địa phương có thuế riêng." },
  { state: "AL", city: "*", general: 0.04, grocery: 0.02, notes: "Bang đánh thuế tạp hoá ở mức giảm." },
  { state: "AR", city: "*", general: 0.065, grocery: 0.00125, notes: "Tạp hoá ở mức giảm rất thấp." },
  { state: "AZ", city: "*", general: 0.056, grocery: 0, notes: "Bang miễn tạp hoá; nhiều thành phố vẫn thu." },
  { state: "AZ", city: "Mesa", general: 0.083, grocery: 0.02 },
  { state: "AZ", city: "Phoenix", general: 0.086, grocery: 0.023 },
  { state: "AZ", city: "Tucson", general: 0.087, grocery: 0.026 },
  { state: "CA", city: "*", general: 0.0725, grocery: 0, notes: "Miễn thuế phần lớn thực phẩm chưa chế biến." },
  { state: "CA", city: "Anaheim", general: 0.0775, grocery: 0 },
  { state: "CA", city: "Bakersfield", general: 0.0825, grocery: 0 },
  { state: "CA", city: "Fresno", general: 0.0835, grocery: 0 },
  { state: "CA", city: "Garden Grove", general: 0.0875, grocery: 0 },
  { state: "CA", city: "Irvine", general: 0.0775, grocery: 0 },
  { state: "CA", city: "Long Beach", general: 0.1025, grocery: 0 },
  { state: "CA", city: "Los Angeles", general: 0.095, grocery: 0 },
  { state: "CA", city: "Oakland", general: 0.1025, grocery: 0 },
  { state: "CA", city: "Riverside", general: 0.0875, grocery: 0 },
  { state: "CA", city: "Sacramento", general: 0.0875, grocery: 0 },
  { state: "CA", city: "San Bernardino", general: 0.0875, grocery: 0 },
  { state: "CA", city: "San Diego", general: 0.0775, grocery: 0 },
  { state: "CA", city: "San Francisco", general: 0.08625, grocery: 0 },
  { state: "CA", city: "San Jose", general: 0.09375, grocery: 0 },
  { state: "CA", city: "Santa Ana", general: 0.0925, grocery: 0 },
  { state: "CA", city: "Stockton", general: 0.09, grocery: 0 },
  { state: "CA", city: "Westminster", general: 0.0875, grocery: 0 },
  { state: "CO", city: "*", general: 0.029, grocery: 0, notes: "Bang miễn tạp hoá." },
  { state: "CO", city: "Colorado Springs", general: 0.082, grocery: 0 },
  { state: "CO", city: "Denver", general: 0.0881, grocery: 0 },
  { state: "CT", city: "*", general: 0.0635, grocery: 0, notes: "Bang miễn tạp hoá." },
  { state: "CT", city: "Hartford", general: 0.0635, grocery: 0 },
  { state: "DC", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "DC", city: "Washington", general: 0.06, grocery: 0 },
  { state: "DE", city: "*", general: 0, grocery: 0, notes: "Không có thuế bán hàng." },
  { state: "FL", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "FL", city: "Fort Lauderdale", general: 0.07, grocery: 0 },
  { state: "FL", city: "Jacksonville", general: 0.075, grocery: 0 },
  { state: "FL", city: "Miami", general: 0.07, grocery: 0 },
  { state: "FL", city: "Orlando", general: 0.065, grocery: 0 },
  { state: "FL", city: "Tampa", general: 0.075, grocery: 0 },
  { state: "GA", city: "*", general: 0.04, grocery: 0, notes: "Bang miễn tạp hoá; địa phương có thể thu." },
  { state: "GA", city: "Atlanta", general: 0.089, grocery: 0.04 },
  { state: "GA", city: "Savannah", general: 0.07, grocery: 0.03 },
  { state: "HI", city: "*", general: 0.04, grocery: 0.04, notes: "General Excise Tax áp cho gần như mọi thứ." },
  { state: "HI", city: "Honolulu", general: 0.04712, grocery: 0.04712 },
  { state: "IA", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "ID", city: "*", general: 0.06, grocery: 0.06, notes: "Đánh thuế tạp hoá, bù bằng tín thuế cuối năm." },
  { state: "IL", city: "*", general: 0.0625, grocery: 0.01, notes: "Tạp hoá mức giảm 1%." },
  { state: "IL", city: "Aurora", general: 0.0825, grocery: 0.01 },
  { state: "IL", city: "Chicago", general: 0.1025, grocery: 0.01 },
  { state: "IN", city: "*", general: 0.07, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "IN", city: "Indianapolis", general: 0.07, grocery: 0 },
  { state: "KS", city: "*", general: 0.065, grocery: 0, notes: "Bang đã bỏ thuế tạp hoá; địa phương có thể còn." },
  { state: "KY", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "LA", city: "*", general: 0.05, grocery: 0, notes: "Bang miễn tạp hoá; địa phương thu nhiều." },
  { state: "LA", city: "Baton Rouge", general: 0.0995, grocery: 0.055 },
  { state: "LA", city: "New Orleans", general: 0.0945, grocery: 0.05 },
  { state: "MA", city: "*", general: 0.0625, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "MA", city: "Boston", general: 0.0625, grocery: 0 },
  { state: "MD", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "MD", city: "Baltimore", general: 0.06, grocery: 0 },
  { state: "ME", city: "*", general: 0.055, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "MI", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "MI", city: "Detroit", general: 0.06, grocery: 0 },
  { state: "MN", city: "*", general: 0.06875, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "MN", city: "Minneapolis", general: 0.08025, grocery: 0 },
  { state: "MN", city: "St. Paul", general: 0.07875, grocery: 0 },
  { state: "MO", city: "*", general: 0.04225, grocery: 0.01225, notes: "Tạp hoá mức giảm." },
  { state: "MO", city: "Kansas City", general: 0.086, grocery: 0.056 },
  { state: "MO", city: "St. Louis", general: 0.09679, grocery: 0.06679 },
  { state: "MS", city: "*", general: 0.07, grocery: 0.07, notes: "Đánh thuế tạp hoá đầy đủ." },
  { state: "MT", city: "*", general: 0, grocery: 0, notes: "Không có thuế bán hàng." },
  { state: "NC", city: "*", general: 0.0475, grocery: 0.02, notes: "Tạp hoá chịu thuế địa phương 2%." },
  { state: "NC", city: "Charlotte", general: 0.0725, grocery: 0.02 },
  { state: "NC", city: "Raleigh", general: 0.0725, grocery: 0.02 },
  { state: "ND", city: "*", general: 0.05, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "NE", city: "*", general: 0.055, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "NH", city: "*", general: 0, grocery: 0, notes: "Không có thuế bán hàng." },
  { state: "NJ", city: "*", general: 0.06625, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "NJ", city: "Jersey City", general: 0.06625, grocery: 0 },
  { state: "NJ", city: "Newark", general: 0.06625, grocery: 0 },
  { state: "NM", city: "*", general: 0.04875, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "NM", city: "Albuquerque", general: 0.07625, grocery: 0 },
  { state: "NV", city: "*", general: 0.0685, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "NV", city: "Las Vegas", general: 0.08375, grocery: 0 },
  { state: "NV", city: "Reno", general: 0.08265, grocery: 0 },
  { state: "NY", city: "*", general: 0.04, grocery: 0, notes: "Miễn phần lớn thực phẩm." },
  { state: "NY", city: "Buffalo", general: 0.0875, grocery: 0 },
  { state: "NY", city: "New York", general: 0.08875, grocery: 0 },
  { state: "NY", city: "Rochester", general: 0.08, grocery: 0 },
  { state: "NY", city: "Yonkers", general: 0.08875, grocery: 0 },
  { state: "OH", city: "*", general: 0.0575, grocery: 0, notes: "Miễn thực phẩm mang về." },
  { state: "OH", city: "Cincinnati", general: 0.078, grocery: 0 },
  { state: "OH", city: "Cleveland", general: 0.08, grocery: 0 },
  { state: "OH", city: "Columbus", general: 0.075, grocery: 0 },
  { state: "OK", city: "*", general: 0.045, grocery: 0, notes: "Bang đã bỏ thuế tạp hoá; địa phương còn thu." },
  { state: "OK", city: "Oklahoma City", general: 0.08625, grocery: 0.04125 },
  { state: "OK", city: "Tulsa", general: 0.08517, grocery: 0.04017 },
  { state: "OR", city: "*", general: 0, grocery: 0, notes: "Không có thuế bán hàng." },
  { state: "OR", city: "Portland", general: 0, grocery: 0 },
  { state: "PA", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "PA", city: "Philadelphia", general: 0.08, grocery: 0 },
  { state: "PA", city: "Pittsburgh", general: 0.07, grocery: 0 },
  { state: "RI", city: "*", general: 0.07, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "SC", city: "*", general: 0.06, grocery: 0, notes: "Bang miễn tạp hoá." },
  { state: "SD", city: "*", general: 0.042, grocery: 0.042, notes: "Đánh thuế tạp hoá đầy đủ." },
  { state: "TN", city: "*", general: 0.07, grocery: 0.04, notes: "Tạp hoá mức giảm 4%." },
  { state: "TN", city: "Memphis", general: 0.0975, grocery: 0.0675 },
  { state: "TN", city: "Nashville", general: 0.0925, grocery: 0.0625 },
  { state: "TX", city: "*", general: 0.0625, grocery: 0, notes: "Miễn thực phẩm cơ bản." },
  { state: "TX", city: "Arlington", general: 0.0825, grocery: 0 },
  { state: "TX", city: "Austin", general: 0.0825, grocery: 0 },
  { state: "TX", city: "Dallas", general: 0.0825, grocery: 0 },
  { state: "TX", city: "El Paso", general: 0.0825, grocery: 0 },
  { state: "TX", city: "Fort Worth", general: 0.0825, grocery: 0 },
  { state: "TX", city: "Houston", general: 0.0825, grocery: 0 },
  { state: "TX", city: "Plano", general: 0.0825, grocery: 0 },
  { state: "TX", city: "San Antonio", general: 0.0825, grocery: 0 },
  { state: "UT", city: "*", general: 0.0485, grocery: 0.0175, notes: "Tạp hoá mức giảm." },
  { state: "UT", city: "Salt Lake City", general: 0.0775, grocery: 0.03 },
  { state: "VA", city: "*", general: 0.053, grocery: 0.01, notes: "Tạp hoá chỉ chịu phần địa phương 1%." },
  { state: "VA", city: "Richmond", general: 0.06, grocery: 0.01 },
  { state: "VA", city: "Virginia Beach", general: 0.06, grocery: 0.01 },
  { state: "VT", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "WA", city: "*", general: 0.065, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "WA", city: "Bellevue", general: 0.103, grocery: 0 },
  { state: "WA", city: "Seattle", general: 0.1025, grocery: 0 },
  { state: "WA", city: "Spokane", general: 0.09, grocery: 0 },
  { state: "WA", city: "Tacoma", general: 0.103, grocery: 0 },
  { state: "WI", city: "*", general: 0.05, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "WI", city: "Milwaukee", general: 0.079, grocery: 0 },
  { state: "WV", city: "*", general: 0.06, grocery: 0, notes: "Miễn tạp hoá." },
  { state: "WY", city: "*", general: 0.04, grocery: 0, notes: "Miễn tạp hoá." }
];

export const taxJurisdictionCount = 132;
export const taxStateCount = 51;
export const taxCityCount = 81;
